### ISSUE TITLE
Copyright headers missing

### ISSUE THREAD

**Issue by lganzzzo** [krishpranav/memecraft#2]
Hello,

Even though Oat++ has `Apache 2.0` license - you can not drop copyright headers from files.
Please restore all Oat++ copyright headers in ALL files.

Regards,
Leonid

**Comment by krishpranav** [comment]
hey @lganzzzo sorry for removing the apache 2.0 license from the files I am just taking the code that you done and doing some extra features sorry for removing the license

**Comment by lganzzzo** [comment]
Hey @krishpranav ,

No problem. 
You may add your own headers above Oat++ headers. But Oat++ headers should remain.

**Comment by krishpranav** [comment]
ok thanks @lganzzzo

**Comment by krishpranav** [comment]
thanks for being kind
